# Find associated musical artists (bandmates), and groups associated with Richard Thompson.
# Results show a problem with the coded metadata (value duplication on separate properties).
# Run this query on the DBpedia endpoint: http://dbpedia.org/snorql/
# or, see the corresponding RESULTS file (json).

PREFIX dbo: <http://dbpedia.org/ontology/>

SELECT DISTINCT ?band ?associate

WHERE {

  { ?s ?p <http://dbpedia.org/resource/Richard_Thompson_(musician)> ; dbo:associatedBand ?band }
UNION
  { ?s ?p <http://dbpedia.org/resource/Richard_Thompson_(musician)> ; dbo:associatedMusicalArtist ?associate }

}