# Find associated musical artists (bandmates), and groups associated with Richard Thompson.
# Results an issue with the encoded metadata; values are duplicated on separate properties.
# You can run this query on the DBpedia endpoint: http://dbpedia.org/snorql/
# or, see the attached "RESULTS" file (in JSON).

PREFIX dbo: <http://dbpedia.org/ontology/>

SELECT DISTINCT ?band ?associate

WHERE {

  { ?s ?p <http://dbpedia.org/resource/Richard_Thompson_(musician)> ; dbo:associatedBand ?band }
UNION
  { ?s ?p <http://dbpedia.org/resource/Richard_Thompson_(musician)> ; dbo:associatedMusicalArtist ?associate }

}