# flugelhorn-playing associates : Freddie Hubbard : still alive 
# Run this query on the DBpedia endpoint: http://dbpedia.org/snorql/.
# or, see the corresponding RESULTS file (csv).

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT DISTINCT ?associateLabel

WHERE {

  { ?s ?p <http://dbpedia.org/resource/Freddie_Hubbard> ; dbo:associatedMusicalArtist ?associate .
    ?associate dbo:instrument dbr:Flugelhorn ;
              rdfs:label ?associateLabel .
}

FILTER NOT EXISTS { ?associate dbo:deathDate ?ddate }
FILTER (lang(?associateLabel) = "en")

}